# Parameters for ctc controller

# Robot type
n_gears:         2             # number of possible gear selection
goal:           [0,0]          # target state

# General 
hysteresis:      true          # true or false hysteresis mode
min_delay:       0.5           #

# CTC only
w0:              1.0

# Sliding only
lam:             1.0
nab:             1.0
D:               1.0

# Roll Only
horizon:         0.5           #
sim_dt:          0.1           #
